parameters:
  jobs: []

jobs:
  - ${{ each job in parameters.jobs }}: # Each job
      - ${{ each pair in job }}:          # Insert all properties other than "steps"
          ${{ if ne(pair.key, 'steps') }}:
            ${{ pair.key }}: ${{ pair.value }}
        pool:
          vmImage: 'ubuntu-latest'
        container: septimalmind/izumi-env:jdk11-5
        steps:
          - ${{ job.steps }}
