# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - develop

variables:
- group: security-tokens

jobs:
  - template: .azure-dockerstep.yml
    parameters:
      jobs:
        - job: build
          displayName: 'Tests and Coverage'
          steps:
            - script: |
                  bash travis.sh coverage
              env:
                OPENSSL_KEY: $(openssl.key)
                OPENSSL_IV: $(openssl.iv)
                TOKEN_NPM: $(token.npm)
                TOKEN_NUGET: $(token.nuget)
                TOKEN_CODECOV: $(token.codecov)
            - task: PublishTestResults@2
        - job: sbt
          displayName: 'SBT plugin tests'
          steps:
            - script: |
                bash travis.sh scripted
              env:
                OPENSSL_KEY: $(openssl.key)
                OPENSSL_IV: $(openssl.iv)
                TOKEN_NPM: $(token.npm)
                TOKEN_NUGET: $(token.nuget)
                TOKEN_CODECOV: $(token.codecov)
        - job: site
          dependsOn: build
          displayName: 'Publish Site'
          steps:
            - script: |
                bash travis.sh unpack site
              env:
                OPENSSL_KEY: $(openssl.key)
                OPENSSL_IV: $(openssl.iv)
                TOKEN_NPM: $(token.npm)
                TOKEN_NUGET: $(token.nuget)
                TOKEN_CODECOV: $(token.codecov)
        - job: publish
            displayName: 'Publish to Maven Central'
            dependsOn: build
            steps:
              - script: |
                  bash travis.sh unpack publish
                env:
                  OPENSSL_KEY: $(openssl.key)
                  OPENSSL_IV: $(openssl.iv)
                  TOKEN_NPM: $(token.npm)
                  TOKEN_NUGET: $(token.nuget)
                  TOKEN_CODECOV: $(token.codecov)
