# https://aka.ms/yaml

trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - series/*

variables:
  - group: security-tokens
  - name: COURSIER_CACHE
    value: $(Pipeline.Workspace)/.coursier
  - name: IVY_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.ivy2

jobs:
  - template: .azure-dockerstep.yml
    parameters:
      jobs:
        - job: build_212
          displayName: 'Tests and Coverage: 2.12'
          steps:
            - script: |
                bash sbtgen.sc --js
                bash .build.sh 2.12 coverage
            - task: PublishTestResults@2
            - task: PublishCodeCoverageResults@1
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/**/cobertura.xml'
        - job: build_213
          displayName: 'Tests and Coverage: 2.13'
          steps:
            - script: |
                bash sbtgen.sc --js
                bash .build.sh 2.13 coverage
            - task: PublishTestResults@2
            - task: PublishCodeCoverageResults@1
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/**/cobertura.xml'
        - job: site
          dependsOn:
            - build_212
            - build_213
          displayName: 'Publish Site'
          steps:
            - script: |
                bash sbtgen.sc --js
                bash .build.sh secrets site
#        - job: publish
#          displayName: 'Publish to Maven Central'
#          dependsOn:
#            - build_212
#            - build_213
#          steps:
#            - script: |
#                bash sbtgen.sc --js --native
#                bash .build.sh scala-all secrets publishScala
        - job: publish211
          displayName: 'Publish to Maven Central 2.12'
          dependsOn:
            - build_212
          steps:
            - script: |
                bash sbtgen.sc --js --native
                bash .build.sh 2.11 secrets publishScala
        - job: publish212
          displayName: 'Publish to Maven Central 2.12'
          dependsOn:
            - build_212
          steps:
            - script: |
                bash sbtgen.sc --js
                bash .build.sh 2.12 secrets publishScala
        - job: publish213
          displayName: 'Publish to Maven Central 2.13'
          dependsOn:
            - build_213
          steps:
            - script: |
                bash sbtgen.sc --js
                bash .build.sh 2.13 secrets publishScala
