# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - develop

variables:
- group: security-tokens

jobs:
  - template: .azure-dockerstep.yml
    parameters:
      jobs:
        - job: build
          displayName: 'Tests and Coverage'
          steps:
            - script: |
                  bash travis.sh coverage
            - task: PublishTestResults@2
            - task: PublishCodeCoverageResults@1
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: './target/scala-2.12/coverage-report/cobertura.xml'
        - job: sbt
          displayName: 'SBT plugin tests'
          steps:
            - script: |
                bash travis.sh scripted
        - job: site
          #dependsOn: build
          displayName: 'Publish Site'
          steps:
            - script: |
                bash travis.sh unpack site
        - job: publish
          displayName: 'Publish to Maven Central'
          dependsOn: build
          steps:
            - script: |
                bash travis.sh unpack publish
