parameters:
  jobs: []

jobs:
  - ${{ each job in parameters.jobs }}: # Each job
      - ${{ each pair in job }}:          # Insert all properties other than "steps"
          ${{ if ne(pair.key, 'steps') }}:
            ${{ pair.key }}: ${{ pair.value }}
        pool:
          vmImage: 'ubuntu-latest'
        container: septimalmind/izumi-env:jdk11-5
        steps:
          - script: |
               echo "CPU:"
               cat /proc/cpuinfo
               echo "RAM:"
               free -h
               echo "DISK":
               df -h
               echo "ENVIRONMENT:"
               printenv
            displayName: "Diagnostics"
          - ${{ job.steps }}
            env:
              OPENSSL_KEY: $(openssl.key)
              OPENSSL_IV: $(openssl.iv)
              TOKEN_NPM: $(token.npm)
              TOKEN_NUGET: $(token.nuget)
              TOKEN_CODECOV: $(token.codecov)
