parameters:
  jobs: []

jobs:
  - ${{ each job in parameters.jobs }}:
      - ${{ each pair in job }}:
          ${{ if ne(pair.key, 'steps') }}:
            ${{ pair.key }}: ${{ pair.value }}
        pool:
          vmImage: 'ubuntu-latest'
        container: septimalmind/izumi-env:jdk11-6
        steps:
          - task: CacheBeta@0
            inputs:
              key: coursier | $(Agent.OS)
              path: $(COURSIER_CACHE)
            displayName: Cache Coursier Packages
          - task: CacheBeta@0
            inputs:
              key: ivy | $(Agent.OS)
              path: $(IVY_CACHE_FOLDER)
            displayName: Cache Ivy Packages
          - script: |
               echo "CPU:"
               cat /proc/cpuinfo
               echo "RAM:"
               free -h
               echo "DISK":
               df -h
               echo "ENVIRONMENT:"
               printenv
            displayName: "Diagnostics"
          - ${{ each step in job.steps }}:
              - ${{ each pair in step }}:
                  ${{ pair.key }}: ${{ pair.value }}
                env:
                  OPENSSL_KEY: $(openssl.key)
                  OPENSSL_IV: $(openssl.iv)
                  TOKEN_NPM: $(token.npm)
                  TOKEN_NUGET: $(token.nuget)
                  TOKEN_CODECOV: $(token.codecov)
