# https://aka.ms/yaml

pr:
  branches:
    include:
    - '*'

trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - series/*

variables:
  - group: security-tokens
  - name: COURSIER_CACHE
    value: $(Pipeline.Workspace)/.coursier
  - name: IVY_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.ivy2

jobs:
  - template: .azure-dockerstep.yml
    parameters:
      jobs:
        - job: build_212
          displayName: 'Tests and Coverage: 2.12'
          steps:
            - script: |
                bash sbtgen.sc --js && bash .build.sh 2.12 coverage
            - task: PublishTestResults@2
            - task: PublishCodeCoverageResults@1
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/**/cobertura.xml'
        - job: build_213
          displayName: 'Tests and Coverage: 2.13'
          steps:
            - script: |
                bash sbtgen.sc --js && bash .build.sh 2.13 coverage
            - task: PublishTestResults@2
            - task: PublishCodeCoverageResults@1
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/target/**/cobertura.xml'
        - job: site
          dependsOn:
            - build_212
            - build_213
          displayName: 'Publish Site'
          steps:
            - script: |
                echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
                echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
              displayName: Use JDK 11 for docs build
            - script: |
                bash sbtgen.sc --js && bash .build.sh 2.13 secrets site
        - job: publish212
          displayName: 'Publish to Maven Central (2.12)'
          dependsOn:
            - build_212
          steps:
            - script: |
                bash sbtgen.sc --js && bash .build.sh 2.12 secrets publishScala
        - job: publish213
          displayName: 'Publish to Maven Central (2.13)'
          dependsOn:
            - build_213
          steps:
            - script: |
                bash sbtgen.sc --js && bash .build.sh 2.13 secrets publishScala
