updates.pin  = [
  # use only Scala3 3.9 LTS (planned Q2 2026, requires JDK 17+)
  { groupId = "org.scala-lang", artifactId="scala3-compiler", version = "3.9." },
  { groupId = "org.scala-lang", artifactId="scala3-library", version = "3.9." },
  { groupId = "org.scala-lang", artifactId="scala3-library_sjs1", version = "3.9." }
]

pullRequests.frequency = "@monthly"

pullRequests.grouping = [
  # group scala updates & scoverage
  { name="scala-versions", "title"="Scala compiler updates", "filter"=[{"group" = "org.scala-lang"}, {"group" = "org.scoverage"}] },
  # group everything else
  { name = "all", "title" = "Dependency updates", "filter" = [{"group" = "*"}] }
]

updatePullRequests = "always"
