language: scala
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
scala:
  - 2.12.4
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_b9da041c62db_key -iv $encrypted_b9da041c62db_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
jobs:
  include:
    - stage: versionate
      script: sbt ++$TRAVIS_SCALA_VERSION "addVersionSuffix $TRAVIS_BRANCH"
    - stage: build
      script: sbt ++$TRAVIS_SCALA_VERSION clean test publishSigned
    - stage: release
      script: sbt ++$TRAVIS_SCALA_VERSION sonatypeRelease
stages:
  - name: versionate
    if: NOT ((branch = master) OR (branch = develop))
  - name: build
  - name: release
    if: tag =~ ^v
