sudo: required
dist: trusty

services:
- docker

before_install:
  - mkdir -p ~/.sbt/
  - mkdir -p ~/.sbt/1.0/plugins/
  - mkdir -p ~/.m2/
  - mkdir -p ~/.ivy2/
  - mkdir -p ~/.coursier/
  - mkdir -p ~/.cache/coursier
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M8")' > ~/.sbt/1.0/plugins/build.sbt
  - sudo rm -rf ~/.ivy2/local
  - sudo find ~/.m2/ ~/.ivy2/ ~/.sbt/ ~/.coursier/ ~/.cache/coursier -name '*izumi*' -prune -exec rm -rf "{}" \;
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  - npm whoami

before_script:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"

branches:
  except:
  - gh-pages

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.cache/coursier
  - $HOME/.m2

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 2 $HOME/.m2/
  - du -h -d 2 $HOME/.coursier/
  - du -h -d 2 $HOME/.cache/coursier/
  - sudo find $HOME/.sbt -name "*.lock" -type f -delete
  - sudo find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - sudo rm -rf ~/.ivy2/local
  - sudo find ~/.m2/ ~/.ivy2/ ~/.sbt/ ~/.coursier/ ~/.cache/coursier -name '*izumi*' -prune -exec rm -rf "{}" \;

env:
  - IMAGE="septimalmind/izumi-env:jdk11-2"

jobs:
  include:
    - stage: "Publish"
      script: bash docker.sh versionate publish
    - stage: "Tests & Coverage"
      script: bash docker.sh coverage
    - stage: "SBT Tests"
      script: bash docker.sh scripted
    - stage: "Site"
      script: bash docker.sh versionate site
