sudo: required
dist: trusty


language: scala

#language: csharp
#solution: solution-name.sln
#go:
#  - "1.10"

jdk:
  - oraclejdk9

scala:
  - 2.12.6

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install mono-complete
  - sudo apt-get remove scala-library scala
  - sudo wget www.scala-lang.org/files/archive/scala-2.12.6.deb
  - sudo dpkg -i scala-2.12.6.deb
  - sudo apt-get update
  - sudo apt-get install scala
  - jdk_switcher use oraclejdk9
  - npm i -g 'typescript@2.9.2'
  - GIMME_OUTPUT="$(gimme 1.10 | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
  - echo "Go `go version`"
  - echo "TS `tsc -version`"
  - echo "Java `java -version`"

before_script:
  - bash travis.sh versionate

script:
  - bash travis.sh coverage
  - bash travis.sh scripted

before_deploy:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  - openssl aes-256-cbc -K $encrypted_8eadf24ba628_key -iv $encrypted_8eadf24ba628_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - ln -s .secrets/local.sbt local.sbt
  - chmod 600 .secrets/travis-deploy-key
  - eval "$(ssh-agent -s)"
  - ssh-add .secrets/travis-deploy-key

deploy:
  - provider: script
    script: bash travis.sh deploy
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false


# Some static settings
branches:
  except:
  - gh-pages

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.m2

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
