language: scala
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.m2
scala:
  - 2.12.6
jdk:
  - oraclejdk9
before_install:
  - ( openssl aes-256-cbc -K $encrypted_b9da041c62db_key -iv $encrypted_b9da041c62db_iv -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar ) || true
script:
  - bash travis.sh build

after_success:
  - bash travis.sh report
