# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - develop

variables:
- group: security-tokens

jobs:
  - job: build
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          docker.sh coverage
        displayName: 'Tests and Coverage'
  - job: sbt
    pool: 
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          docker.sh scripted
        displayName: 'SBT plugin tests'
  - job: site
    pool: 
      vmImage: 'ubuntu-latest' 
    dependsOn: build
    steps:
      - script: |
          docker.sh site
        displayName: 'Publish Site'
  - job: publish
    pool: 
      vmImage: 'ubuntu-latest'
    dependsOn: build
    steps:
      - script: |
          docker.sh publish
        displayName: 'Publish to Maven Central'
