# https://aka.ms/yaml

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - develop

variables:
- group: security-tokens

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    export IMAGE="septimalmind/izumi-env:jdk11-5"
    export SOURCEDIR=$(pwd)
    export CNAME="izumi-build-$(date +%s)"
    export RESOURCEDIR="$( cd "$(dirname "$0")" ; pwd -P )"
    export HOMEDIR="$( cd ~ ; pwd -P )"

    if [[ "$TRAVIS_PULL_REQUEST" == "false"  ]] ; then
      openssl aes-256-cbc -K $(openssl.key) -iv $(openssl.iv) -in secrets.tar.enc -out secrets.tar -d
      tar xvf secrets.tar
      ln -s .secrets/local.sbt local.sbt
    fi

    docker pull $IMAGE

    docker run --rm --name $CNAME \
        -e TRAVIS_BRANCH=$BUILD_SOURCEBRANCH \
        -e TRAVIS_TAG=$BUILD_SOURCEBRANCH \
        -e TRAVIS_PULL_REQUEST=false \
        -e TRAVIS_BUILD_NUMBER=$BUILD_BUILDID \
        -e NPM_TOKEN=$(token.npm) \
        -e NUGET_TOKEN=$(token.nuget) \
        -e CODECOV_TOKEN=$(token.codecov) \
        --volume "${SOURCEDIR}":/work:z \
        --volume "${HOMEDIR}":/root:z \
        $IMAGE bash -xe travis.sh coverage scripted
  displayName: 'Build'
