package izumi.distage.reflection.macros

sealed trait FunctoidDummyImplicit

final abstract class UnresolvedOnlyFunctoidDummyImplicit extends FunctoidDummyImplicit

final abstract class IndiscriminateFunctoidDummyImplicit extends FunctoidDummyImplicit
