package izumi.distage.reflection.macros

sealed trait FunctoidDummyImplicit

final abstract class IgnorableFunctoidDummyImplicit extends FunctoidDummyImplicit

final abstract class UnignorableDummyImplicit extends FunctoidDummyImplicit
