package izumi.distage.config.model

import izumi.distage.model.definition.DIStageAnnotation

/**
  * Attaches a `$comment` field with the contents of the annotation to
  * config's JSON Schema generated by ConfigWriter.
  *
  * {{{
  *   @ConfigDoc("this is an example config")
  *   final case class ExampleConf(
  *    @ConfigDoc("this is an example field")
  *    intField: Int,
  *   )
  * }}}
  *
  * @see [[izumi.distage.roles.bundled.ConfigWriter]]
  * @see [[izumi.distage.roles.bundled.JsonSchemaGenerator]]
  */
final class ConfigDoc(val doc: String) extends DIStageAnnotation
