// DO NOT EDIT THIS FILE
// IT IS AUTOGENERATED BY `sbtgen.sc` SCRIPT
// ALL CHANGES WILL BE LOST
// https://www.scala-js.org/
addSbtPlugin("org.scala-js" % "sbt-scalajs" % PV.scala_js_version)

// https://github.com/portable-scala/sbt-crossproject
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")

////////////////////////////////////////////////////////////////////////////////

addSbtPlugin("io.7mind.izumi.sbt" % "sbt-izumi" % "0.0.115")

addSbtPlugin("com.github.sbt" % "sbt-pgp" % PV.sbt_pgp)

addSbtPlugin("org.scoverage" % "sbt-scoverage" % PV.sbt_scoverage)

addSbtPlugin("com.github.sbt" % "sbt-unidoc" % PV.sbt_unidoc)

addSbtPlugin("com.github.sbt" % "sbt-site" % PV.sbt_site)

addSbtPlugin("com.github.sbt" % "sbt-site-paradox" % PV.sbt_site)

addSbtPlugin("com.github.sbt" % "sbt-ghpages" % PV.sbt_ghpages)

addSbtPlugin("com.lightbend.paradox" % "sbt-paradox" % PV.sbt_paradox)

addSbtPlugin("com.lightbend.paradox" % "sbt-paradox-theme" % PV.sbt_paradox)

addSbtPlugin("org.scalameta" % "sbt-mdoc" % PV.sbt_mdoc)

// Ignore scala-xml version conflict between scoverage where `coursier` requires scala-xml v2
// and scoverage requires scala-xml v1 on Scala 2.12,
// introduced when updating scoverage from 1.9.3 to 2.0.5
libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
