addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.4.4")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.22.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.5.12")
addSbtPlugin("io.7mind.izumi" % "sbt-distage-testkit-js" % sys.props("coverage.host-version"))
addSbtPlugin("io.7mind.izumi" % "sbt-distage-testkit-native" % sys.props("coverage.host-version"))
