name: Build

on: [push, pull_request]

jobs:
  build-scala:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
        scala: [ '2.12', '2.13']
    steps:
      - uses: actions/checkout@v3
      - uses: rlespinasse/github-slug-action@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java }}
      - name: Caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
            /usr/local/bin/cs
          key: ${{ runner.os }}-scala
      - name: Install Coursier
        run:
          if [[ ! -f /usr/local/bin/cs ]]; then
            sudo curl -Lo /usr/local/bin/cs  https://git.io/coursier-cli-linux
            cat /usr/local/bin/cs
            sudo chmod +x /usr/local/bin/cs
          fi
      - name: Build and Test
        env:
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
        run: |
          bash sbtgen.sc --js
          bash .build.sh ${{ matrix.scala }} coverage